### PR TITLE
[ADD] Coding Dodo

### PR DESCRIPTION
**Pull request by PhilDL**
Coding Dodo is a blog about Odoo focused on latest version (v14)
- In depth articles and analysis
- Long series about OWL

### CODE REVIEW

**Review by desdelinux — CHANGES_REQUESTED** [review]
This site is not accessible, review your link

**Comment by PhilDL** [comment]
I'm really sorry, shouldn't do PR that late. Fixed it.

**Review by desdelinux — APPROVED** [review]

**Comment by desdelinux** [comment]
@PhilDL Would be nice if you could still squash the commits

**Comment by desdelinux** [comment]
Thanks @PhilDL Here you can see how to combine your commit https://onthedock.github.io/post/210121-combinar-commits/

So we try to keep the repo clean

**Comment by PhilDL** [comment]
I gave up and closed the PR, I forgot to force push after the squash and don't know how to fix it.

**Comment by desdelinux** [comment]
@phildl You can create a new pr with a single commit :).

**Pull request closed without merging**
