### PR TITLE
Update URL Implementatiom

### PR DESCRIPTION
**Pull request by gomezgleonardob**
Update URL Slides

### CODE REVIEW

**Comment by desdelinux** [comment]
@gomezgleonardob Please, resolve conflicts

**Comment by gomezgleonardob** [comment]
Conflicts, resolved

**Comment by desdelinux** [comment]
> Conflicts, resolved

Squash commit, please.

**Comment by desdelinux** [comment]
@codiumAI-Agent /review

**Comment by desdelinux** [comment]
@CodiumAI-Agent /review

**Comment by desdelinux** [comment]
@CodiumAI-Agent /describe

**Pull request closed without merging**
